name: Claude PR Comment Review
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Vollständige Git-History für Diff-Analyse
          
      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Review the pull request that triggered this workflow.
            Focus on:
            - Security vulnerabilities and input validation
            - Code correctness and potential bugs
            - Code quality and best practices
            
            Provide specific, actionable feedback with line numbers.
            Only comment on files that were changed in this PR.
